INSERT INTO "Exercise" (id_exercise, title, description, difficulty, topic, "expectedSql", "isActive", "createdAt") VALUES

-- EASY (30)
(gen_random_uuid(), 'SELECT básico', 'Obtén todos los registros de la tabla usuarios.', 'EASY', 'SELECT', 'SELECT * FROM usuarios', true, NOW()),
(gen_random_uuid(), 'SELECT con WHERE', 'Obtén los usuarios con edad mayor a 18.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE edad > 18', true, NOW()),
(gen_random_uuid(), 'SELECT columnas', 'Obtén solo los nombres y emails de los usuarios.', 'EASY', 'SELECT', 'SELECT nombre, email FROM usuarios', true, NOW()),
(gen_random_uuid(), 'SELECT ordenado', 'Obtén los usuarios ordenados por nombre.', 'EASY', 'SELECT', 'SELECT * FROM usuarios ORDER BY nombre ASC', true, NOW()),
(gen_random_uuid(), 'SELECT con alias', 'Obtén nombre como "Nombre" y edad como "Edad".', 'EASY', 'SELECT', 'SELECT nombre AS "Nombre", edad AS "Edad" FROM usuarios', true, NOW()),
(gen_random_uuid(), 'SELECT con LIMIT', 'Obtén los primeros 5 usuarios.', 'EASY', 'SELECT', 'SELECT * FROM usuarios LIMIT 5', true, NOW()),
(gen_random_uuid(), 'SELECT DISTINCT', 'Obtén las ciudades distintas de los usuarios.', 'EASY', 'SELECT', 'SELECT DISTINCT ciudad FROM usuarios', true, NOW()),
(gen_random_uuid(), 'LIKE empieza con', 'Obtén los usuarios cuyo nombre empiece con A.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE nombre LIKE ''A%''', true, NOW()),
(gen_random_uuid(), 'LIKE contiene', 'Obtén los usuarios cuyo nombre contenga "an".', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE nombre LIKE ''%an%''', true, NOW()),
(gen_random_uuid(), 'IS NULL', 'Obtén los usuarios sin email registrado.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE email IS NULL', true, NOW()),
(gen_random_uuid(), 'IS NOT NULL', 'Obtén los usuarios con email registrado.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE email IS NOT NULL', true, NOW()),
(gen_random_uuid(), 'BETWEEN edades', 'Obtén los usuarios con edad entre 18 y 30.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE edad BETWEEN 18 AND 30', true, NOW()),
(gen_random_uuid(), 'INSERT básico', 'Inserta un usuario con nombre Juan y email juan@email.com.', 'EASY', 'INSERT', 'INSERT INTO usuarios (nombre, email) VALUES (''Juan'', ''juan@email.com'')', true, NOW()),
(gen_random_uuid(), 'INSERT con columnas', 'Inserta un usuario con nombre, email, edad y ciudad.', 'EASY', 'INSERT', 'INSERT INTO usuarios (nombre, email, edad, ciudad) VALUES (''Ana'', ''ana@email.com'', 25, ''La Paz'')', true, NOW()),
(gen_random_uuid(), 'UPDATE por id', 'Actualiza el nombre del usuario con id 1 a Pedro.', 'EASY', 'UPDATE', 'UPDATE usuarios SET nombre = ''Pedro'' WHERE id = 1', true, NOW()),
(gen_random_uuid(), 'UPDATE por nombre', 'Actualiza el email de los usuarios llamados Juan.', 'EASY', 'UPDATE', 'UPDATE usuarios SET email = ''nuevo@email.com'' WHERE nombre = ''Juan''', true, NOW()),
(gen_random_uuid(), 'DELETE por id', 'Elimina el usuario con id 1.', 'EASY', 'DELETE', 'DELETE FROM usuarios WHERE id = 1', true, NOW()),
(gen_random_uuid(), 'DELETE por condición', 'Elimina los usuarios inactivos.', 'EASY', 'DELETE', 'DELETE FROM usuarios WHERE activo = false', true, NOW()),
(gen_random_uuid(), 'INNER JOIN', 'Obtén el nombre del usuario y el nombre de su pedido.', 'EASY', 'JOIN', 'SELECT usuarios.nombre, pedidos.nombre FROM usuarios INNER JOIN pedidos ON usuarios.id = pedidos.id_usuario', true, NOW()),
(gen_random_uuid(), 'LEFT JOIN', 'Obtén todos los usuarios y sus pedidos.', 'EASY', 'JOIN', 'SELECT usuarios.nombre, pedidos.nombre FROM usuarios LEFT JOIN pedidos ON usuarios.id = pedidos.id_usuario', true, NOW()),
(gen_random_uuid(), 'COUNT', 'Cuenta el total de usuarios.', 'EASY', 'AGGREGATE', 'SELECT COUNT(*) FROM usuarios', true, NOW()),
(gen_random_uuid(), 'AVG', 'Obtén el promedio de edad de los usuarios.', 'EASY', 'AGGREGATE', 'SELECT AVG(edad) FROM usuarios', true, NOW()),
(gen_random_uuid(), 'COUNT DISTINCT', 'Cuenta cuántas ciudades distintas hay.', 'EASY', 'AGGREGATE', 'SELECT COUNT(DISTINCT ciudad) FROM usuarios', true, NOW()),
(gen_random_uuid(), 'SUM', 'Obtén la suma total de todos los pedidos.', 'EASY', 'AGGREGATE', 'SELECT SUM(total) FROM pedidos', true, NOW()),
(gen_random_uuid(), 'MIN y MAX', 'Obtén la edad mínima y máxima.', 'EASY', 'AGGREGATE', 'SELECT MIN(edad), MAX(edad) FROM usuarios', true, NOW()),
(gen_random_uuid(), 'GROUP BY COUNT', 'Cuenta usuarios por ciudad.', 'EASY', 'GROUP_BY', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad', true, NOW()),
(gen_random_uuid(), 'ORDER BY DESC', 'Obtén usuarios ordenados por edad descendente.', 'EASY', 'SELECT', 'SELECT * FROM usuarios ORDER BY edad DESC', true, NOW()),
(gen_random_uuid(), 'CREATE TABLE', 'Crea una tabla productos con id, nombre y precio.', 'EASY', 'DDL', 'CREATE TABLE productos (id SERIAL PRIMARY KEY, nombre VARCHAR(100), precio DECIMAL(10,2))', true, NOW()),
(gen_random_uuid(), 'COMMIT', 'Confirma la transacción actual.', 'EASY', 'TCL', 'COMMIT', true, NOW()),
(gen_random_uuid(), 'ROLLBACK', 'Deshace la transacción actual.', 'EASY', 'TCL', 'ROLLBACK', true, NOW()),

-- MEDIUM (35)
(gen_random_uuid(), 'SELECT con AND', 'Obtén los usuarios activos mayores de 25.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE activo = true AND edad > 25', true, NOW()),
(gen_random_uuid(), 'SELECT con IN', 'Obtén usuarios de La Paz, Cochabamba o Santa Cruz.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE ciudad IN (''La Paz'', ''Cochabamba'', ''Santa Cruz'')', true, NOW()),
(gen_random_uuid(), 'SELECT con OR', 'Obtén usuarios con rol admin o mayores de 30.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE rol = ''admin'' OR edad > 30', true, NOW()),
(gen_random_uuid(), 'SELECT con BETWEEN y AND', 'Obtén usuarios activos con edad entre 18 y 30.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE edad BETWEEN 18 AND 30 AND activo = true', true, NOW()),
(gen_random_uuid(), 'LIKE con NOT', 'Obtén usuarios cuyo nombre no empiece con A.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE nombre NOT LIKE ''A%''', true, NOW()),
(gen_random_uuid(), 'INSERT múltiple', 'Inserta dos usuarios en una sentencia.', 'MEDIUM', 'INSERT', 'INSERT INTO usuarios (nombre, email) VALUES (''Luis'', ''luis@email.com''), (''Maria'', ''maria@email.com'')', true, NOW()),
(gen_random_uuid(), 'INSERT desde SELECT', 'Inserta en clientes los usuarios activos.', 'MEDIUM', 'INSERT', 'INSERT INTO clientes (nombre, email) SELECT nombre, email FROM usuarios WHERE activo = true', true, NOW()),
(gen_random_uuid(), 'UPDATE múltiples campos', 'Actualiza nombre y email del usuario con id 5.', 'MEDIUM', 'UPDATE', 'UPDATE usuarios SET nombre = ''Carlos'', email = ''carlos@email.com'' WHERE id = 5', true, NOW()),
(gen_random_uuid(), 'UPDATE con incremento', 'Incrementa en 1 la edad de los usuarios activos.', 'MEDIUM', 'UPDATE', 'UPDATE usuarios SET edad = edad + 1 WHERE activo = true', true, NOW()),
(gen_random_uuid(), 'DELETE con AND', 'Elimina usuarios inactivos menores de edad.', 'MEDIUM', 'DELETE', 'DELETE FROM usuarios WHERE activo = false AND edad < 18', true, NOW()),
(gen_random_uuid(), 'DELETE con OR', 'Elimina usuarios de La Paz o con rol invitado.', 'MEDIUM', 'DELETE', 'DELETE FROM usuarios WHERE ciudad = ''La Paz'' OR rol = ''invitado''', true, NOW()),
(gen_random_uuid(), 'JOIN con alias', 'Obtén usuario y total del pedido con alias u y p.', 'MEDIUM', 'JOIN', 'SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario', true, NOW()),
(gen_random_uuid(), 'RIGHT JOIN', 'Obtén todos los pedidos con sus usuarios.', 'MEDIUM', 'JOIN', 'SELECT usuarios.nombre, pedidos.nombre FROM usuarios RIGHT JOIN pedidos ON usuarios.id = pedidos.id_usuario', true, NOW()),
(gen_random_uuid(), 'JOIN múltiple', 'Obtén usuario, pedido y categoría.', 'MEDIUM', 'JOIN', 'SELECT u.nombre, p.nombre, c.nombre FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario INNER JOIN categorias c ON p.id_categoria = c.id', true, NOW()),
(gen_random_uuid(), 'JOIN con GROUP BY', 'Obtén cantidad de pedidos por usuario.', 'MEDIUM', 'JOIN', 'SELECT u.nombre, COUNT(p.id) FROM usuarios u LEFT JOIN pedidos p ON u.id = p.id_usuario GROUP BY u.nombre', true, NOW()),
(gen_random_uuid(), 'GROUP BY AVG', 'Obtén el promedio de edad por ciudad.', 'MEDIUM', 'GROUP_BY', 'SELECT ciudad, AVG(edad) FROM usuarios GROUP BY ciudad', true, NOW()),
(gen_random_uuid(), 'GROUP BY con WHERE', 'Cuenta usuarios activos por ciudad.', 'MEDIUM', 'GROUP_BY', 'SELECT ciudad, COUNT(*) FROM usuarios WHERE activo = true GROUP BY ciudad', true, NOW()),
(gen_random_uuid(), 'GROUP BY multi-columna', 'Cuenta usuarios por ciudad y rol.', 'MEDIUM', 'GROUP_BY', 'SELECT ciudad, rol, COUNT(*) FROM usuarios GROUP BY ciudad, rol', true, NOW()),
(gen_random_uuid(), 'GROUP BY con SUM', 'Obtén suma de ventas por vendedor.', 'MEDIUM', 'GROUP_BY', 'SELECT id_vendedor, SUM(total) FROM ventas GROUP BY id_vendedor', true, NOW()),
(gen_random_uuid(), 'HAVING con COUNT', 'Obtén ciudades con más de 3 usuarios.', 'MEDIUM', 'HAVING', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad HAVING COUNT(*) > 3', true, NOW()),
(gen_random_uuid(), 'HAVING con SUM', 'Obtén vendedores con ventas mayores a 10000.', 'MEDIUM', 'HAVING', 'SELECT id_vendedor, SUM(total) FROM ventas GROUP BY id_vendedor HAVING SUM(total) > 10000', true, NOW()),
(gen_random_uuid(), 'Subconsulta IN', 'Obtén usuarios con al menos un pedido.', 'MEDIUM', 'SUBQUERY', 'SELECT * FROM usuarios WHERE id IN (SELECT id_usuario FROM pedidos)', true, NOW()),
(gen_random_uuid(), 'Subconsulta EXISTS', 'Obtén usuarios con pedidos mayores a 500.', 'MEDIUM', 'SUBQUERY', 'SELECT * FROM usuarios WHERE EXISTS (SELECT 1 FROM pedidos WHERE pedidos.id_usuario = usuarios.id AND pedidos.total > 500)', true, NOW()),
(gen_random_uuid(), 'Subconsulta en SELECT', 'Obtén nombre y total de pedidos como columna.', 'MEDIUM', 'SUBQUERY', 'SELECT nombre, (SELECT COUNT(*) FROM pedidos WHERE pedidos.id_usuario = usuarios.id) AS total_pedidos FROM usuarios', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE ADD COLUMN', 'Agrega columna stock a productos.', 'MEDIUM', 'DDL', 'ALTER TABLE productos ADD COLUMN stock INT', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE ADD CONSTRAINT', 'Agrega UNIQUE al email en usuarios.', 'MEDIUM', 'DDL', 'ALTER TABLE usuarios ADD CONSTRAINT unique_email UNIQUE (email)', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE ADD CHECK', 'Agrega CHECK precio > 0 en productos.', 'MEDIUM', 'DDL', 'ALTER TABLE productos ADD CHECK (precio > 0)', true, NOW()),
(gen_random_uuid(), 'CREATE TABLE con DEFAULT', 'Crea empleados con salario DEFAULT 0.', 'MEDIUM', 'DDL', 'CREATE TABLE empleados (id SERIAL PRIMARY KEY, nombre VARCHAR(100), salario DECIMAL(10,2) DEFAULT 0)', true, NOW()),
(gen_random_uuid(), 'GRANT INSERT', 'Otorga INSERT en pedidos al vendedor.', 'MEDIUM', 'DCL', 'GRANT INSERT ON pedidos TO vendedor', true, NOW()),
(gen_random_uuid(), 'BEGIN TRANSACTION', 'Inicia una nueva transacción.', 'MEDIUM', 'TCL', 'BEGIN TRANSACTION', true, NOW()),
(gen_random_uuid(), 'Min y Max con GROUP BY', 'Obtén edad mínima y máxima por ciudad.', 'MEDIUM', 'AGGREGATE', 'SELECT ciudad, MIN(edad), MAX(edad) FROM usuarios GROUP BY ciudad', true, NOW()),
(gen_random_uuid(), 'LIKE con AND', 'Obtén usuarios activos con email que contenga admin.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE email LIKE ''%admin%'' AND activo = true', true, NOW()),
(gen_random_uuid(), 'ORDER BY múltiple', 'Obtén usuarios ordenados por ciudad y nombre.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios ORDER BY ciudad ASC, nombre ASC', true, NOW()),
(gen_random_uuid(), 'JOIN con WHERE', 'Obtén usuarios sin pedidos.', 'MEDIUM', 'JOIN', 'SELECT usuarios.nombre FROM usuarios LEFT JOIN pedidos ON usuarios.id = pedidos.id_usuario WHERE pedidos.id IS NULL', true, NOW()),
(gen_random_uuid(), 'GROUP BY con ORDER BY', 'Obtén ciudades ordenadas por cantidad de usuarios.', 'MEDIUM', 'GROUP_BY', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad ORDER BY COUNT(*) DESC', true, NOW()),

-- HARD (35)
(gen_random_uuid(), 'SELECT con CASE', 'Clasifica usuarios por edad: Joven, Adulto, Adulto Mayor.', 'HARD', 'SELECT', 'SELECT nombre, CASE WHEN edad < 18 THEN ''Joven'' WHEN edad < 60 THEN ''Adulto'' ELSE ''Adulto Mayor'' END AS categoria_edad FROM usuarios', true, NOW()),
(gen_random_uuid(), 'SELECT con COALESCE', 'Obtén nombre y email mostrando "Sin email" si es NULL.', 'HARD', 'SELECT', 'SELECT nombre, COALESCE(email, ''Sin email'') AS email FROM usuarios', true, NOW()),
(gen_random_uuid(), 'Subconsulta escalar', 'Obtén usuarios en la misma ciudad que el usuario 1.', 'HARD', 'SELECT', 'SELECT * FROM usuarios WHERE ciudad = (SELECT ciudad FROM usuarios WHERE id = 1)', true, NOW()),
(gen_random_uuid(), 'ORDER BY DESC y ASC', 'Obtén usuarios ordenados por ciudad ASC y edad DESC.', 'HARD', 'SELECT', 'SELECT * FROM usuarios ORDER BY ciudad ASC, edad DESC', true, NOW()),
(gen_random_uuid(), 'LIKE múltiples', 'Obtén usuarios con nombre que empiece con A o M.', 'HARD', 'SELECT', 'SELECT * FROM usuarios WHERE nombre LIKE ''A%'' OR nombre LIKE ''M%'' ORDER BY nombre ASC', true, NOW()),
(gen_random_uuid(), 'INSERT SELECT con WHERE', 'Inserta en clientes los usuarios mayores de 18.', 'HARD', 'INSERT', 'INSERT INTO clientes (nombre, email) SELECT nombre, email FROM usuarios WHERE edad > 18', true, NOW()),
(gen_random_uuid(), 'INSERT con JOIN y HAVING', 'Inserta en premium_users los que tienen más de 5 pedidos.', 'HARD', 'INSERT', 'INSERT INTO premium_users (id_usuario, nombre) SELECT u.id, u.nombre FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario GROUP BY u.id, u.nombre HAVING COUNT(p.id) > 5', true, NOW()),
(gen_random_uuid(), 'UPDATE con CASE', 'Actualiza rol: admin a superadmin, user a client.', 'HARD', 'UPDATE', 'UPDATE usuarios SET rol = CASE WHEN rol = ''admin'' THEN ''superadmin'' WHEN rol = ''user'' THEN ''client'' ELSE rol END', true, NOW()),
(gen_random_uuid(), 'UPDATE con subquery', 'Marca como inactivos usuarios sin pedidos.', 'HARD', 'UPDATE', 'UPDATE usuarios SET activo = false WHERE id NOT IN (SELECT id_usuario FROM pedidos)', true, NOW()),
(gen_random_uuid(), 'DELETE con NOT IN', 'Elimina usuarios sin pedidos.', 'HARD', 'DELETE', 'DELETE FROM usuarios WHERE id NOT IN (SELECT id_usuario FROM pedidos)', true, NOW()),
(gen_random_uuid(), 'DELETE con subconsulta', 'Elimina usuarios sin pedidos completados.', 'HARD', 'DELETE', 'DELETE FROM usuarios WHERE id NOT IN (SELECT id_usuario FROM pedidos WHERE estado = ''completado'')', true, NOW()),
(gen_random_uuid(), 'SELF JOIN', 'Obtén empleados con su jefe.', 'HARD', 'JOIN', 'SELECT e1.nombre AS empleado, e2.nombre AS jefe FROM empleados e1 INNER JOIN empleados e2 ON e1.id_jefe = e2.id', true, NOW()),
(gen_random_uuid(), 'FULL OUTER JOIN', 'Obtén todos los usuarios y pedidos.', 'HARD', 'JOIN', 'SELECT usuarios.nombre, pedidos.nombre FROM usuarios FULL OUTER JOIN pedidos ON usuarios.id = pedidos.id_usuario', true, NOW()),
(gen_random_uuid(), 'CROSS JOIN', 'Obtén combinaciones de usuarios y categorías.', 'HARD', 'JOIN', 'SELECT usuarios.nombre, categorias.nombre FROM usuarios CROSS JOIN categorias', true, NOW()),
(gen_random_uuid(), 'JOIN con ORDER BY y LIMIT', 'Obtén los 5 usuarios con más pedidos.', 'HARD', 'JOIN', 'SELECT u.nombre, COUNT(p.id) AS total_pedidos FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario GROUP BY u.nombre ORDER BY total_pedidos DESC LIMIT 5', true, NOW()),
(gen_random_uuid(), 'GROUP BY con HAVING', 'Obtén ciudades con más de 5 usuarios.', 'HARD', 'GROUP_BY', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad HAVING COUNT(*) > 5', true, NOW()),
(gen_random_uuid(), 'GROUP BY con JOIN', 'Obtén por usuario cantidad y total de pedidos.', 'HARD', 'GROUP_BY', 'SELECT u.nombre, COUNT(p.id), SUM(p.total) FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario GROUP BY u.nombre', true, NOW()),
(gen_random_uuid(), 'HAVING múltiple', 'Obtén ciudades con más de 3 usuarios y edad promedio mayor a 20.', 'HARD', 'HAVING', 'SELECT ciudad, COUNT(*), AVG(edad) FROM usuarios GROUP BY ciudad HAVING COUNT(*) > 3 AND AVG(edad) > 20', true, NOW()),
(gen_random_uuid(), 'Subconsulta ANY', 'Obtén usuarios mayores que cualquiera de La Paz.', 'HARD', 'SUBQUERY', 'SELECT * FROM usuarios WHERE edad > ANY (SELECT edad FROM usuarios WHERE ciudad = ''La Paz'')', true, NOW()),
(gen_random_uuid(), 'Subconsulta ALL', 'Obtén usuarios mayores que todos de La Paz.', 'HARD', 'SUBQUERY', 'SELECT * FROM usuarios WHERE edad > ALL (SELECT edad FROM usuarios WHERE ciudad = ''La Paz'')', true, NOW()),
(gen_random_uuid(), 'Subconsulta en FROM', 'Obtén promedio de totales por usuario.', 'HARD', 'SUBQUERY', 'SELECT AVG(total_usuario) FROM (SELECT SUM(total) AS total_usuario FROM pedidos GROUP BY id_usuario) AS sub', true, NOW()),
(gen_random_uuid(), 'CREATE TABLE con FK', 'Crea tabla pedidos con clave foránea.', 'HARD', 'DDL', 'CREATE TABLE pedidos (id SERIAL PRIMARY KEY, id_usuario INT REFERENCES usuarios(id), total DECIMAL(10,2))', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE DROP COLUMN', 'Elimina la columna stock de productos.', 'HARD', 'DDL', 'ALTER TABLE productos DROP COLUMN stock', true, NOW()),
(gen_random_uuid(), 'DROP TABLE IF EXISTS', 'Elimina la tabla temp_ventas si existe.', 'HARD', 'DDL', 'DROP TABLE IF EXISTS temp_ventas', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE RENAME COLUMN', 'Renombra nombre a nombre_completo.', 'HARD', 'DDL', 'ALTER TABLE usuarios RENAME COLUMN nombre TO nombre_completo', true, NOW()),
(gen_random_uuid(), 'REVOKE', 'Revoca SELECT en usuarios al invitado.', 'HARD', 'DCL', 'REVOKE SELECT ON usuarios FROM invitado', true, NOW()),
(gen_random_uuid(), 'SAVEPOINT y ROLLBACK', 'Crea savepoint, inserta y vuelve atrás.', 'HARD', 'TCL', 'SAVEPOINT sp1; INSERT INTO usuarios (nombre, email) VALUES (''Temp'', ''temp@email.com''); ROLLBACK TO SAVEPOINT sp1', true, NOW()),
(gen_random_uuid(), 'CASE con GROUP BY', 'Cuenta usuarios por categoría de edad.', 'HARD', 'SELECT', 'SELECT CASE WHEN edad < 18 THEN ''Menor'' WHEN edad < 60 THEN ''Adulto'' ELSE ''Adulto Mayor'' END AS categoria, COUNT(*) FROM usuarios GROUP BY categoria', true, NOW()),
(gen_random_uuid(), 'WITH (CTE)', 'Crea CTE de usuarios activos y selecciónalos.', 'HARD', 'SELECT', 'WITH usuarios_activos AS (SELECT * FROM usuarios WHERE activo = true) SELECT * FROM usuarios_activos', true, NOW()),
(gen_random_uuid(), 'WITH con JOIN', 'Crea CTE de pedidos recientes y combínala con usuarios.', 'HARD', 'SELECT', 'WITH pedidos_recientes AS (SELECT * FROM pedidos WHERE fecha >= ''2024-01-01'') SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos_recientes p ON u.id = p.id_usuario', true, NOW()),
(gen_random_uuid(), 'ROW_NUMBER OVER', 'Asigna número de fila ordenado por edad.', 'HARD', 'SELECT', 'SELECT nombre, edad, ROW_NUMBER() OVER (ORDER BY edad DESC) AS posicion FROM usuarios', true, NOW()),
(gen_random_uuid(), 'RANK OVER PARTITION BY', 'Rankea usuarios por edad dentro de cada ciudad.', 'HARD', 'SELECT', 'SELECT nombre, ciudad, edad, RANK() OVER (PARTITION BY ciudad ORDER BY edad DESC) AS rank_ciudad FROM usuarios', true, NOW()),
(gen_random_uuid(), 'UNION', 'Obtén ciudades de usuarios y clientes sin duplicados.', 'HARD', 'SELECT', 'SELECT ciudad FROM usuarios UNION SELECT ciudad FROM clientes', true, NOW()),
(gen_random_uuid(), 'UNION ALL con ORDER BY', 'Obtén nombres de usuarios y clientes ordenados.', 'HARD', 'SELECT', 'SELECT nombre FROM usuarios UNION ALL SELECT nombre FROM clientes ORDER BY nombre ASC', true, NOW()),
(gen_random_uuid(), 'CAST', 'Convierte edad a texto.', 'HARD', 'SELECT', 'SELECT nombre, CAST(edad AS TEXT) FROM usuarios', true, NOW()),

-- +50 nuevos ejercicios (15 EASY + 17 MEDIUM + 18 HARD)
(gen_random_uuid(), 'SELECT con WHERE menor que', 'Obtén usuarios menores de 18 años.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE edad < 18', true, NOW()),
(gen_random_uuid(), 'SELECT con WHERE NOT', 'Obtén usuarios que no estén activos.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE NOT activo', true, NOW()),
(gen_random_uuid(), 'SELECT con alias de tabla', 'Obtén nombre y email usando alias u.', 'EASY', 'SELECT', 'SELECT u.nombre, u.email FROM usuarios u', true, NOW()),
(gen_random_uuid(), 'SELECT con ORDER BY DESC y LIMIT', 'Obtén los 3 usuarios más jóvenes.', 'EASY', 'SELECT', 'SELECT * FROM usuarios ORDER BY edad ASC LIMIT 3', true, NOW()),
(gen_random_uuid(), 'LIKE termina con', 'Obtén usuarios con email de gmail.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE email LIKE ''%@gmail.com''', true, NOW()),
(gen_random_uuid(), 'INSERT con DEFAULT VALUES', 'Inserta un usuario usando valores por defecto.', 'EASY', 'INSERT', 'INSERT INTO usuarios DEFAULT VALUES', true, NOW()),
(gen_random_uuid(), 'UPDATE con AND', 'Actualiza el email de usuarios de La Paz que sean activos.', 'EASY', 'UPDATE', 'UPDATE usuarios SET email = ''nuevo@email.com'' WHERE ciudad = ''La Paz'' AND activo = true', true, NOW()),
(gen_random_uuid(), 'DELETE con BETWEEN', 'Elimina usuarios con edad entre 18 y 25.', 'EASY', 'DELETE', 'DELETE FROM usuarios WHERE edad BETWEEN 18 AND 25', true, NOW()),
(gen_random_uuid(), 'JOIN con USING', 'Obtén usuarios y pedidos usando USING.', 'EASY', 'JOIN', 'SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos p USING(id)', true, NOW()),
(gen_random_uuid(), 'GROUP BY con COUNT y ORDER', 'Cuenta usuarios por ciudad y ordena.', 'EASY', 'GROUP_BY', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad ORDER BY COUNT(*)', true, NOW()),
(gen_random_uuid(), 'Subconsulta NOT IN', 'Obtén usuarios sin pedidos.', 'EASY', 'SUBQUERY', 'SELECT * FROM usuarios WHERE id NOT IN (SELECT id_usuario FROM pedidos)', true, NOW()),
(gen_random_uuid(), 'CREATE TABLE con UNIQUE', 'Crea tabla usuarios con email único.', 'EASY', 'DDL', 'CREATE TABLE usuarios (id SERIAL PRIMARY KEY, email VARCHAR(100) UNIQUE)', true, NOW()),
(gen_random_uuid(), 'CREATE TABLE con TEXT', 'Crea tabla productos con descripción.', 'EASY', 'DDL', 'CREATE TABLE productos (id SERIAL PRIMARY KEY, nombre VARCHAR(100), descripcion TEXT)', true, NOW()),
(gen_random_uuid(), 'COUNT con WHERE', 'Cuenta usuarios activos.', 'EASY', 'AGGREGATE', 'SELECT COUNT(*) FROM usuarios WHERE activo = true', true, NOW()),
(gen_random_uuid(), 'LIKE con underscore', 'Obtén usuarios con nombre de 5 letras.', 'EASY', 'SELECT', 'SELECT * FROM usuarios WHERE nombre LIKE ''_____''', true, NOW()),

(gen_random_uuid(), 'SELECT con NOT BETWEEN', 'Obtén usuarios fuera del rango 18-65.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE edad NOT BETWEEN 18 AND 65', true, NOW()),
(gen_random_uuid(), 'SELECT con ORDER BY múltiple y WHERE', 'Obtén usuarios activos ordenados por ciudad y edad.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE activo = true ORDER BY ciudad ASC, edad DESC', true, NOW()),
(gen_random_uuid(), 'SELECT con NOT LIKE', 'Obtén usuarios cuyo nombre no empiece con A.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE nombre NOT LIKE ''A%''', true, NOW()),
(gen_random_uuid(), 'SELECT con IN y ORDER BY', 'Obtén usuarios de 3 ciudades ordenados.', 'MEDIUM', 'SELECT', 'SELECT * FROM usuarios WHERE ciudad IN (''La Paz'', ''Cochabamba'', ''Santa Cruz'') ORDER BY nombre', true, NOW()),
(gen_random_uuid(), 'INSERT con ON CONFLICT', 'Inserta un usuario y si existe actualiza.', 'MEDIUM', 'INSERT', 'INSERT INTO usuarios (nombre, email) VALUES (''Juan'', ''juan@email.com'') ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre', true, NOW()),
(gen_random_uuid(), 'INSERT SELECT con WHERE', 'Copia usuarios activos a clientes.', 'MEDIUM', 'INSERT', 'INSERT INTO clientes (nombre, email, ciudad) SELECT nombre, email, ciudad FROM usuarios WHERE activo = true', true, NOW()),
(gen_random_uuid(), 'UPDATE con cálculo', 'Incrementa un 10% el total de pedidos.', 'MEDIUM', 'UPDATE', 'UPDATE pedidos SET total = total * 1.1 WHERE estado = ''completado''', true, NOW()),
(gen_random_uuid(), 'UPDATE con subconsulta EXISTS', 'Actualiza email de usuarios con pedidos.', 'MEDIUM', 'UPDATE', 'UPDATE usuarios SET email = CONCAT(email, ''.vip'') WHERE EXISTS (SELECT 1 FROM pedidos WHERE pedidos.id_usuario = usuarios.id)', true, NOW()),
(gen_random_uuid(), 'DELETE con IN', 'Elimina usuarios de La Paz o Cochabamba.', 'MEDIUM', 'DELETE', 'DELETE FROM usuarios WHERE ciudad IN (''La Paz'', ''Cochabamba'')', true, NOW()),
(gen_random_uuid(), 'LEFT JOIN con IS NULL', 'Obtén usuarios sin pedidos.', 'MEDIUM', 'JOIN', 'SELECT u.nombre FROM usuarios u LEFT JOIN pedidos p ON u.id = p.id_usuario WHERE p.id IS NULL', true, NOW()),
(gen_random_uuid(), 'JOIN con WHERE y ORDER BY', 'Obtén pedidos completados con usuario ordenados.', 'MEDIUM', 'JOIN', 'SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario WHERE p.estado = ''completado'' ORDER BY p.total DESC', true, NOW()),
(gen_random_uuid(), 'GROUP BY con SUM y AVG', 'Obtén suma y promedio de edad por ciudad.', 'MEDIUM', 'GROUP_BY', 'SELECT ciudad, SUM(edad), AVG(edad) FROM usuarios GROUP BY ciudad', true, NOW()),
(gen_random_uuid(), 'GROUP BY con MAX y WHERE', 'Obtén edad máxima por ciudad de activos.', 'MEDIUM', 'GROUP_BY', 'SELECT ciudad, MAX(edad) FROM usuarios WHERE activo = true GROUP BY ciudad', true, NOW()),
(gen_random_uuid(), 'HAVING con MIN', 'Obtén ciudades con edad mínima mayor a 15.', 'MEDIUM', 'HAVING', 'SELECT ciudad, MIN(edad) FROM usuarios GROUP BY ciudad HAVING MIN(edad) > 15', true, NOW()),
(gen_random_uuid(), 'HAVING con MAX y ORDER BY', 'Obtén ciudades con edad máxima menor a 50 ordenado.', 'MEDIUM', 'HAVING', 'SELECT ciudad, MAX(edad) FROM usuarios GROUP BY ciudad HAVING MAX(edad) < 50 ORDER BY ciudad', true, NOW()),
(gen_random_uuid(), 'Subconsulta correlacionada EXISTS', 'Obtén usuarios con pedidos mayores a 1000.', 'MEDIUM', 'SUBQUERY', 'SELECT * FROM usuarios WHERE EXISTS (SELECT 1 FROM pedidos WHERE pedidos.id_usuario = usuarios.id AND pedidos.total > 1000)', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE SET NOT NULL', 'Agrega NOT NULL a la columna email.', 'MEDIUM', 'DDL', 'ALTER TABLE usuarios ALTER COLUMN email SET NOT NULL', true, NOW()),
(gen_random_uuid(), 'GRANT ALL', 'Otorga todos los permisos en usuarios al admin.', 'MEDIUM', 'DCL', 'GRANT ALL ON usuarios TO admin', true, NOW()),
(gen_random_uuid(), 'COMMIT después de INSERT', 'Inserta un registro y confirma.', 'MEDIUM', 'TCL', 'INSERT INTO usuarios (nombre, email) VALUES (''Test'', ''test@email.com''); COMMIT', true, NOW()),

(gen_random_uuid(), 'SELECT con LIMIT y OFFSET', 'Obtén 5 usuarios saltando los primeros 3.', 'HARD', 'SELECT', 'SELECT * FROM usuarios LIMIT 5 OFFSET 3', true, NOW()),
(gen_random_uuid(), 'SELECT con CASE en ORDER BY', 'Ordena usuarios por categoría de edad.', 'HARD', 'SELECT', 'SELECT nombre, edad FROM usuarios ORDER BY CASE WHEN edad >= 60 THEN 3 WHEN edad >= 18 THEN 2 ELSE 1 END DESC', true, NOW()),
(gen_random_uuid(), 'SELECT con múltiples JOIN', 'Obtén usuario, pedido y categoría con alias.', 'HARD', 'SELECT', 'SELECT u.nombre, p.nombre, c.nombre FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario INNER JOIN categorias c ON p.id_categoria = c.id', true, NOW()),
(gen_random_uuid(), 'INSERT SELECT con JOIN y WHERE', 'Inserta en clientes usuarios con pedidos > 500.', 'HARD', 'INSERT', 'INSERT INTO clientes (nombre, email) SELECT DISTINCT u.nombre, u.email FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario WHERE p.total > 500', true, NOW()),
(gen_random_uuid(), 'UPDATE con FROM', 'Actualiza usuarios desde pedidos con JOIN.', 'HARD', 'UPDATE', 'UPDATE usuarios SET activo = true FROM pedidos WHERE usuarios.id = pedidos.id_usuario AND pedidos.total > 1000', true, NOW()),
(gen_random_uuid(), 'DELETE con USING y JOIN', 'Elimina usuarios con pedidos cancelados.', 'HARD', 'DELETE', 'DELETE FROM usuarios USING pedidos WHERE usuarios.id = pedidos.id_usuario AND pedidos.estado = ''cancelado''', true, NOW()),
(gen_random_uuid(), 'NATURAL JOIN', 'Obtén usuarios y pedidos con NATURAL JOIN.', 'HARD', 'JOIN', 'SELECT * FROM usuarios NATURAL INNER JOIN pedidos', true, NOW()),
(gen_random_uuid(), 'JOIN con ON múltiple', 'Obtén usuarios y pedidos con dos condiciones.', 'HARD', 'JOIN', 'SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos p ON u.id = p.id_usuario AND p.estado = ''completado''', true, NOW()),
(gen_random_uuid(), 'GROUP BY con HAVING y ORDER BY', 'Obtén ciudades con más de 2 usuarios ordenado.', 'HARD', 'GROUP_BY', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad HAVING COUNT(*) > 2 ORDER BY COUNT(*) DESC', true, NOW()),
(gen_random_uuid(), 'HAVING con múltiples agregaciones', 'Obtén ciudades con más de 2 usuarios y edad promedio > 25.', 'HARD', 'HAVING', 'SELECT ciudad, COUNT(*), AVG(edad) FROM usuarios GROUP BY ciudad HAVING COUNT(*) > 2 AND AVG(edad) > 25', true, NOW()),
(gen_random_uuid(), 'Subconsulta en HAVING', 'Obtén ciudades con más usuarios que el promedio.', 'HARD', 'SUBQUERY', 'SELECT ciudad, COUNT(*) FROM usuarios GROUP BY ciudad HAVING COUNT(*) > (SELECT AVG(count) FROM (SELECT COUNT(*) AS count FROM usuarios GROUP BY ciudad) AS sub)', true, NOW()),
(gen_random_uuid(), 'Subconsulta múltiple en WHERE', 'Obtén usuarios con pedidos y comentarios.', 'HARD', 'SUBQUERY', 'SELECT * FROM usuarios WHERE id IN (SELECT id_usuario FROM pedidos) AND id IN (SELECT id_usuario FROM comentarios)', true, NOW()),
(gen_random_uuid(), 'ALTER TABLE ADD PRIMARY KEY', 'Agrega clave primaria a productos.', 'HARD', 'DDL', 'ALTER TABLE productos ADD PRIMARY KEY (id)', true, NOW()),
(gen_random_uuid(), 'CREATE INDEX compuesto', 'Crea índice en ciudad y edad.', 'HARD', 'DDL', 'CREATE INDEX idx_ciudad_edad ON usuarios (ciudad, edad)', true, NOW()),
(gen_random_uuid(), 'REVOKE ALL', 'Revoca todos los permisos en usuarios al invitado.', 'HARD', 'DCL', 'REVOKE ALL ON usuarios FROM invitado', true, NOW()),
(gen_random_uuid(), 'SAVEPOINT con RELEASE', 'Crea savepoint, inserta y libera el savepoint.', 'HARD', 'TCL', 'SAVEPOINT sp1; INSERT INTO usuarios (nombre, email) VALUES (''Temp'', ''temp@email.com''); RELEASE SAVEPOINT sp1; COMMIT', true, NOW()),
(gen_random_uuid(), 'MAX y MIN con GROUP BY y HAVING', 'Obtén ciudades con ciertos rangos de edad.', 'HARD', 'AGGREGATE', 'SELECT ciudad, MAX(edad), MIN(edad) FROM usuarios GROUP BY ciudad HAVING MAX(edad) > 50', true, NOW());

-- Totales: 45 EASY + 54 MEDIUM + 52 HARD = 151
